version: "3.1"

services:
  aws-ecs:
    build:
      context: ./
      dockerfile: ./Dockerfile

    container_name: aws-ecs
    ports:
      - 5000:5000

    # bridge - connect to docker container from localhost
    network_mode: bridge
